export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import '../globals.css'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-zinc-100'>{children}</body>
    </html>
  )
}
